# Site Title
title: Audio Import Database

# Description (used in embeds)
description: DreamsUserDB is a website maintained by Kee7702 to show and playback audio imports requested in Dreams, a game by Media Molecule.

# This config value loads Keeterial into your Github Pages 
remote_theme: Kee7702/Keeterial

# Global Navigation (in HTMl) / (nav)
# Presets:
# - Image: <a class="material-icons" href="{ btn link }"><img src="{ img link }"></a>
# - Icon: <a class="material-icons" href="{ btn link }">{ fonts.google.com Icon }</a>
nav: <a class="material-icons" href="/">people</a><a class="material-icons" href="/imports">album</a><a class="material-icons" href="https://audio.dreams.kee7702.tk/">audio_file</a><a class="material-icons" href="/embeds">code</a>

# Default Embed Color (hex) / (theme_color)
theme_color: '#000000'

# Global Footer / (footer)
footer: DreamsUserDB is a website maintained by Kee7702 to show and playback audio imports requested in Dreams, a game by Media Molecule.

# Show build info below the included footer
build_info: true

# Note: Keeterial is currently under development. Expect more config options soon as well as changed usages
# If you need help with any of the values above, feel free to contact me on Discord

# Page Variables (these can be changed per-page)
# Some variables may change usage during development
# nav - Additional navigation relating to the current page
# theme_color - A different embed color for a specific page
# image - A separate image for embeds relating to a page
# headInsert - HTML to insert into <head> on a page
# description - Change the description for a page
