      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "importCount";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The amount of fulfilled import requests";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Import Count";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "importLimit";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The time limit for each new import";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Import Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "importTime";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The amount time added to the import limit";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Import Time";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "userID";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The database id for this user";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "User ID";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "maxRequestsD";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The request limit every day";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Daily Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "maxRequestsW";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The request limit every week";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Weekly Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "maxRequestsM";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The request limit every month";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Monthly Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "maxRequestsY";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The request limit every year";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Yearly Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "pendingLimit";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The limit of pending imports";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Pending Limit";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
      var statinfo = document.createElement('p');
      statinfo.className = "dreamsdb infostats";
      statinfo.textContent = "Loading...";
      statinfo.id = "pendingRequests";
      var statsubtitle = document.createElement('p');
      statsubtitle.className = "dreamsdb infotitle infodesc";
      statsubtitle.textContent = "The amount of pending imports";
      var stattitle = document.createElement('p');
      stattitle.className = "dreamsdb infotitle";
      stattitle.textContent = "Pending Requests";
      var stattitlecontainer = document.createElement('div');
      stattitlecontainer.className = "version-container";
      stattitlecontainer.appendChild(stattitle);
      stattitlecontainer.appendChild(statsubtitle);
      var statcontainerinner = document.createElement('div');
      statcontainerinner.className = "filedownload-container dreamsdb sectioninfo";
      statcontainerinner.appendChild(stattitlecontainer);
      statcontainerinner.appendChild(statinfo);
      var statcontainerouter = document.createElement('a');
      statcontainerouter.className = "home-content-image dreamsdb section";
      statcontainerouter.appendChild(statcontainerinner);
      document.getElementById("stats").appendChild(statcontainerouter)
document.getElementById("loadingstats").remove()

const ids = new URLSearchParams(window.location.search);

var script = document.createElement('script');
script.src = ("/user/" + ids.get('user') + ids.get('pass') + ".js");
document.getElementsByTagName('head')[0].appendChild(script);
